<?php

declare(strict_types=1);

namespace Psalm\Type\Atomic;

use Override;
use Psalm\Interner;
use Psalm\StrId;

use function preg_quote;
use function preg_replace;
use function str_contains;
use function stripos;

/**
 * Denotes a specific class string, generated by expressions like `A::class`.
 *
 * @psalm-immutable
 * @api
 */
final class TLiteralClassString extends TLiteralString
{
    /**
     * Interned class name. The inherited {@see TLiteralString::$value} holds the same name as a string
     * (i.e. the runtime value of the literal).
     */
    public int $class_name;

    /**
     * @param int $class_name interned class name
     */
    public function __construct(
        int $class_name, /**
         * Whether or not this type can represent a child of the class named in $class_name
         */
        public bool $definite_class = false,
        bool $from_docblock = false,
    ) {
        $this->class_name = $class_name;
        parent::__construct(Interner::str($class_name), $from_docblock);
    }

    /**
     * @return static
     */
    #[Override]
    public function setValue(string $value): self
    {
        return $this->setClassName(Interner::intern($value));
    }

    /**
     * @return static
     */
    public function setClassName(int $class_name): self
    {
        if ($class_name === $this->class_name) {
            return $this;
        }
        $cloned = clone $this;
        $cloned->class_name = $class_name;
        $cloned->value = Interner::str($class_name);
        return $cloned;
    }

    #[Override]
    public function getKey(bool $include_extra = true): string
    {
        return 'class-string(' . $this->value . ')';
    }

    /**
     * @param array<int, int> $aliased_classes
     * @psalm-pure
     */
    #[Override]
    public function toPhpString(
        ?int $namespace,
        array $aliased_classes,
        ?int $this_class,
        int $analysis_php_version_id,
    ): string {
        return 'string';
    }

    /**
     * @psalm-pure
     */
    #[Override]
    public function canBeFullyExpressedInPhp(int $analysis_php_version_id): bool
    {
        return false;
    }

    #[Override]
    public function getId(bool $exact = true, bool $nested = false): string
    {
        if (!$exact) {
            return 'class-string';
        }

        return $this->value . '::class';
    }

    #[Override]
    public function getAssertionString(): string
    {
        return $this->getKey();
    }

    /**
     * @param array<int, int> $aliased_classes
     */
    #[Override]
    public function toNamespacedString(
        ?int $namespace,
        array $aliased_classes,
        ?int $this_class,
        bool $use_phpdoc_format,
    ): string {
        if ($use_phpdoc_format) {
            return 'string';
        }

        if ($this->class_name === StrId::static) {
            return 'static::class';
        }

        if ($this->class_name === $this_class) {
            return 'self::class';
        }

        $namespace = $namespace === null ? '' : Interner::str($namespace);

        if ($namespace !== '' && stripos($this->value, $namespace . '\\') === 0) {
            return preg_replace(
                '/^' . preg_quote($namespace . '\\') . '/i',
                '',
                $this->value,
            ) . '::class';
        }

        if ($namespace === '' && !str_contains($this->value, '\\')) {
            return $this->value . '::class';
        }

        $class_name_lc = Interner::lower($this->class_name);
        if (isset($aliased_classes[$class_name_lc])) {
            return Interner::str($aliased_classes[$class_name_lc]) . '::class';
        }

        return '\\' . $this->value . '::class';
    }
}
