build:
  nodes:
    php56:
      environment:
        php: 5.6
    php70:
      environment:
        php: 7.0
    php71:
      environment:
        php: 7.1

checks:
    php: true

build:
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override: [php-scrutinizer-run]
