<?php

declare(strict_types=1);

namespace Psalm\Internal\Codebase;

use PhpParser;
use Psalm\Codebase;
use Psalm\Internal\Analyzer\ProjectAnalyzer;
use Psalm\Internal\MethodIdentifier;
use Psalm\Internal\Provider\NodeDataProvider;
use Psalm\Internal\Type\Comparator\TypeComparisonResult;
use Psalm\Internal\Type\Comparator\UnionTypeComparator;
use Psalm\Interner;
use Psalm\NodeTypeProvider;
use Psalm\Storage\FunctionLikeParameter;
use Psalm\StrId;
use Psalm\Type;
use Psalm\Type\Atomic\TArray;
use Psalm\Type\Atomic\TCallable;
use Psalm\Type\Atomic\TKeyedArray;
use UnexpectedValueException;

use function array_key_exists;
use function assert;
use function count;
use function dirname;
use function explode;
use function max;
use function min;

/**
 * @internal
 *
 * Gets values from the call map array, which stores data about native functions and methods.
 *
 * The call map data files (dictionaries/CallMap_XX.php, generated by bin/stubs/gen_callmap.php from
 * dictionaries/autogen/ and the hand-written dictionaries/override/ files) are plain literal arrays keyed by
 * interned ids (see {@see Interner::hash()}) of the canonical (declared, case-sensitive) names, so that they can
 * be shared by opcache and looked up without any string manipulation:
 *
 * ```
 * [
 *     'functions' => [function name id => non-empty-list<signature>],
 *     'methods' => [class name id => [method name id => non-empty-list<signature>]],
 * ]
 * ```
 *
 * The first signature is the primary one, the following ones (if any) are alternative signatures (overloads).
 * A signature is `[return type string, ...params]`, a param is `[param name id, type string, flags]`,
 * flags being a combination of the `PARAM_*` constants.
 *
 * Every name used in the call maps is preloaded in {@see StrId::STRINGS} (see bin/generate_str_ids.php).
 * @psalm-type CallMapParam = array{int, string, int-mask-of<self::PARAM_*>}
 * @psalm-type CallMapSignature = list{string, ...CallMapParam}
 * @psalm-type CallMap = array{
 *     functions: array<int, non-empty-list<CallMapSignature>>,
 *     methods: array<int, array<int, non-empty-list<CallMapSignature>>>
 * }
 * @psalm-type TaintSinkMap = array{
 *     functions: array<int, non-empty-list<int>>,
 *     methods: array<int, array<int, non-empty-list<int>>>
 * }
 */
final class InternalCallMapHandler
{
    /** The parameter is optional (legacy key syntax: trailing `=`) */
    public const PARAM_OPTIONAL = 1;
    /** The parameter is variadic (legacy key syntax: leading `...`) */
    public const PARAM_VARIADIC = 2;
    /** The parameter is passed by reference, read and written (legacy key syntax: leading `&`, or `&rw `) */
    public const PARAM_BY_REF = 4;
    /**
     * The by-reference parameter is only written (legacy key syntax: `&w `): the type is the type written to
     * the reference (its out type), any type is accepted as input
     */
    public const PARAM_REF_WRITE = 8;
    /** The by-reference parameter is only read (legacy key syntax: `&r `) */
    public const PARAM_REF_READ = 16;

    private const MIN_CALLMAP_VERSION = 70;
    private const MAX_CALLMAP_VERSION = 85;

    private static ?int $loaded_php_major_version = null;
    private static ?int $loaded_php_minor_version = null;

    /**
     * @var CallMap|null
     */
    private static ?array $call_map = null;

    /**
     * Callables of functions, by function id
     *
     * @var array<int, non-empty-list<TCallable>|null>
     */
    private static array $function_callables = [];

    /**
     * Callables of methods, by class name id and method name id
     *
     * @var array<int, array<int, non-empty-list<TCallable>|null>>
     */
    private static array $method_callables = [];

    /**
     * @var TaintSinkMap|null
     */
    private static ?array $taint_sink_map = null;

    /**
     * @param  int|MethodIdentifier $method_id a method id, or a function id
     * @param  list<PhpParser\Node\Arg>   $args
     */
    public static function getCallableFromCallMapById(
        Codebase $codebase,
        int|MethodIdentifier $method_id,
        array $args,
        ?NodeDataProvider $nodes,
    ): TCallable {
        $possible_callables = self::getCallablesFromCallMap($method_id);

        if ($possible_callables === null) {
            throw new UnexpectedValueException(
                'Not expecting $function_param_options to be null for '
                    . ($method_id instanceof MethodIdentifier ? (string) $method_id : Interner::str($method_id)),
            );
        }

        return self::getMatchingCallableFromCallMapOptions(
            $codebase,
            $possible_callables,
            $args,
            $nodes,
            $method_id,
        );
    }

    /**
     * @param  non-empty-list<TCallable>  $callables
     * @param  list<PhpParser\Node\Arg>                 $args
     * @param  int|MethodIdentifier $method_id a method id, or a function id
     */
    public static function getMatchingCallableFromCallMapOptions(
        Codebase $codebase,
        array $callables,
        array $args,
        ?NodeTypeProvider $nodes,
        int|MethodIdentifier $method_id,
    ): TCallable {
        $is_min_max = !$method_id instanceof MethodIdentifier
            && ($method_id === StrId::max || $method_id === StrId::min);

        if (count($callables) === 1) {
            return $callables[0];
        }

        $matching_param_count_callable = null;
        $matching_coerced_param_count_callable = null;

        foreach ($callables as $possible_callable) {
            $possible_function_params = $possible_callable->params;

            assert($possible_function_params !== null);

            $all_args_match = true;
            $type_coerced = false;

            $last_param = count($possible_function_params)
                ? $possible_function_params[count($possible_function_params) - 1]
                : null;

            $mandatory_param_count = count($possible_function_params);

            foreach ($possible_function_params as $i => $possible_function_param) {
                if ($possible_function_param->is_optional) {
                    $mandatory_param_count = $i;
                    break;
                }
            }

            if ($mandatory_param_count > count($args) && !($last_param && $last_param->is_variadic)) {
                continue;
            }

            foreach ($args as $argument_offset => $arg) {
                if ($argument_offset >= count($possible_function_params)) {
                    if (!$last_param || !$last_param->is_variadic) {
                        $all_args_match = false;
                        break;
                    }

                    $function_param = $last_param;
                } else {
                    $function_param = $possible_function_params[$argument_offset];
                }

                $param_type = $function_param->type;

                if (!$param_type) {
                    continue;
                }

                if (!$nodes
                    || !($arg_type = $nodes->getType($arg->value))
                ) {
                    continue;
                }

                if ($arg_type->hasMixed()) {
                    continue;
                }

                if ($arg->unpack && !$function_param->is_variadic) {
                    if ($arg_type->hasArray()) {
                        /**
                         * @var TArray|TKeyedArray
                         */
                        $array_atomic_type = $arg_type->getArray();

                        if ($array_atomic_type instanceof TKeyedArray) {
                            $arg_type = $array_atomic_type->getGenericValueType();
                        } else {
                            $arg_type = $array_atomic_type->type_params[1];
                        }
                    }
                }

                $arg_result = new TypeComparisonResult();

                if (UnionTypeComparator::isContainedBy(
                    $codebase,
                    $arg_type,
                    $param_type,
                    true,
                    true,
                    $arg_result,
                ) || $arg_result->type_coerced) {
                    if ($arg_result->type_coerced) {
                        $type_coerced = true;
                    }

                    continue;
                }

                $all_args_match = false;
                break;
            }

            if (count($args) === count($possible_function_params)) {
                $matching_param_count_callable = $possible_callable;
            }

            if ($all_args_match && (!$type_coerced || $is_min_max)) {
                return $possible_callable;
            }

            if ($all_args_match) {
                $matching_coerced_param_count_callable = $possible_callable;
            }
        }

        if ($matching_coerced_param_count_callable) {
            return $matching_coerced_param_count_callable;
        }

        if ($matching_param_count_callable) {
            return $matching_param_count_callable;
        }

        // if we don't succeed in finding a match, set to the first possible and wait for issues below
        return $callables[0];
    }

    /**
     * @param int|MethodIdentifier $function_id a method id, or a function id
     * @return non-empty-list<TCallable>|null
     */
    public static function getCallablesFromCallMap(int|MethodIdentifier $function_id): ?array
    {
        if ($function_id instanceof MethodIdentifier) {
            $class = $function_id->fq_class_name;
            $method = $function_id->method_name;

            if (isset(self::$method_callables[$class])
                && array_key_exists($method, self::$method_callables[$class])
            ) {
                return self::$method_callables[$class][$method];
            }

            $signatures = self::getCallMap()['methods'][$class][$method] ?? null;

            return self::$method_callables[$class][$method] = $signatures === null
                ? null
                : self::loadCallables($signatures, self::getTaintSinkMap()['methods'][$class][$method] ?? []);
        }

        if (array_key_exists($function_id, self::$function_callables)) {
            return self::$function_callables[$function_id];
        }

        $signatures = self::getCallMap()['functions'][$function_id] ?? null;

        return self::$function_callables[$function_id] = $signatures === null
            ? null
            : self::loadCallables($signatures, self::getTaintSinkMap()['functions'][$function_id] ?? []);
    }

    /**
     * @param non-empty-list<CallMapSignature> $signatures
     * @param list<int> $taint_sinks taint sinks, by param offset
     * @return non-empty-list<TCallable>
     */
    private static function loadCallables(array $signatures, array $taint_sinks): array
    {
        $possible_callables = [];

        foreach ($signatures as $signature) {
            $return_type = Type::parseString($signature[0]);

            $function_params = [];

            $count = count($signature);
            for ($i = 1; $i < $count; $i++) {
                /** @var CallMapParam $param */
                $param = $signature[$i];
                [$name, $type, $flags] = $param;

                $param_type = Type::parseString($type);

                $out_type = null;

                if ($flags & self::PARAM_REF_WRITE) {
                    $out_type = $param_type;
                    $param_type = Type::getMixed();
                }

                $function_param = new FunctionLikeParameter(
                    $name,
                    ($flags & self::PARAM_BY_REF) !== 0,
                    $param_type,
                    $param_type,
                    null,
                    null,
                    ($flags & self::PARAM_OPTIONAL) !== 0,
                    false,
                    ($flags & self::PARAM_VARIADIC) !== 0,
                );

                if ($out_type) {
                    $function_param->out_type = $out_type;
                }

                if ($name === StrId::haystack) {
                    $function_param->expect_variable = true;
                }

                if (isset($taint_sinks[$i - 1])) {
                    $function_param->sinks = $taint_sinks[$i - 1];
                }

                $function_param->signature_type = null;

                $function_params[] = $function_param;
            }

            $possible_callables[] = new TCallable($function_params, $return_type);
        }

        return $possible_callables;
    }

    /**
     * Gets the method/function call map, see the class docblock for the format
     *
     * @return CallMap
     * @psalm-assert !null self::$call_map
     * @psalm-suppress UnresolvableInclude
     * @psalm-external-mutation-free
     */
    public static function getCallMap(): array
    {
        $codebase = ProjectAnalyzer::getInstance()->getCodebase();
        $analyzer_major_version = $codebase->getMajorAnalysisPhpVersion();
        $analyzer_minor_version = $codebase->getMinorAnalysisPhpVersion();

        if (self::$call_map !== null
            && $analyzer_major_version === self::$loaded_php_major_version
            && $analyzer_minor_version === self::$loaded_php_minor_version
        ) {
            return self::$call_map;
        }

        self::clearCache();

        $analyzer_version_int = min(
            self::MAX_CALLMAP_VERSION,
            max(
                self::MIN_CALLMAP_VERSION,
                (int) ($analyzer_major_version . $analyzer_minor_version),
            ),
        );

        /** @var CallMap */
        $call_map = require(dirname(__DIR__, 4) . "/dictionaries/CallMap_$analyzer_version_int.php");

        self::$call_map = $call_map;

        self::$loaded_php_major_version = $analyzer_major_version;
        self::$loaded_php_minor_version = $analyzer_minor_version;

        return self::$call_map;
    }

    /**
     * Gets the taint sinks of internal functions and methods (by param offset),
     * see dictionaries/InternalTaintSinkMap.php
     *
     * @return TaintSinkMap
     * @psalm-assert !null self::$taint_sink_map
     * @psalm-suppress UnresolvableInclude
     * @psalm-external-mutation-free
     */
    private static function getTaintSinkMap(): array
    {
        /** @var TaintSinkMap */
        return self::$taint_sink_map ??= require(dirname(__DIR__, 4) . '/dictionaries/InternalTaintSinkMap.php');
    }

    /**
     * @param int|MethodIdentifier $key a method id, or a function id
     * @psalm-external-mutation-free
     */
    public static function inCallMap(int|MethodIdentifier $key): bool
    {
        // reloads the call map (and clears the caches) if the analysis PHP version changed
        $call_map = self::getCallMap();

        if ($key instanceof MethodIdentifier) {
            return isset($call_map['methods'][$key->fq_class_name][$key->method_name]);
        }

        return isset($call_map['functions'][$key]);
    }

    /**
     * Returns the call map id (a function id or a method id) of a callable string, e.g. `strlen` or `DateTime::format`
     *
     * @psalm-pure
     */
    public static function getIdFromCallableString(string $callable): int|MethodIdentifier
    {
        $parts = explode('::', $callable, 2);

        return isset($parts[1])
            ? new MethodIdentifier(Interner::intern($parts[0]), Interner::intern($parts[1]))
            : Interner::intern($callable);
    }

    /**
     * @psalm-external-mutation-free
     */
    public static function clearCache(): void
    {
        self::$function_callables = [];
        self::$method_callables = [];
    }
}
