<?php

declare(strict_types=1);

namespace Psalm\Internal\Codebase;

use function dirname;

/**
 * Types of the properties of internal classes.
 *
 * The data file (dictionaries/PropertyMap.php, generated by bin/stubs/update-property-map.php) is a plain literal
 * array `[class name id => [property name id => type string]]`, keyed by interned ids (see {@see Interner::hash()})
 * of the canonical (declared, case-sensitive) names, preloaded in {@see \Psalm\StrId::STRINGS}.
 *
 * @internal
 * @psalm-external-mutation-free
 */
final class PropertyMap
{
    /**
     * @var array<int, array<int, string>>|null
     */
    private static ?array $property_map = null;

    /**
     * Gets the property map: class name id => property name id => type
     *
     * @return array<int, array<int, string>>
     * @psalm-external-mutation-free
     */
    public static function getPropertyMap(): array
    {
        /** @var array<int, array<int, string>> */
        return self::$property_map ??= require(dirname(__DIR__, 4) . '/dictionaries/PropertyMap.php');
    }

    /**
     * Returns the mapped properties (property name id => type) of a class, if it's in the map.
     *
     * @param int $class_name class name id
     * @return array<int, string>|null
     * @psalm-external-mutation-free
     */
    public static function getPropertiesForClass(int $class_name): ?array
    {
        return self::getPropertyMap()[$class_name] ?? null;
    }

    /**
     * @param int $class_name class name id
     * @psalm-external-mutation-free
     */
    public static function inPropertyMap(int $class_name): bool
    {
        return isset(self::getPropertyMap()[$class_name]);
    }
}
