<?php

declare(strict_types=1);

namespace Psalm\Tests;

use Override;
use Psalm\Tests\Traits\InvalidCodeAnalysisTestTrait;
use Psalm\Tests\Traits\ValidCodeAnalysisTestTrait;

use function escapeshellarg;
use function exec;
use function implode;

use const PHP_BINARY;

/**
 * The Hack conformance fixtures, transpiled to PHP: Psalm must give each the
 * verdict HHVM gives the original (checked by HackConformanceTest).
 *
 * Generated by bin/hack-conformance/transpile.php from the Hack fixtures in
 * bin/hack-conformance/fixtures/. Do not edit: edit the fixtures and regenerate.
 */
final class HackConformanceTranspiledTest extends TestCase
{
    use InvalidCodeAnalysisTestTrait;
    use ValidCodeAnalysisTestTrait;

    /**
     * Transpiles the fixtures again before any case runs, so that every case
     * fails if this file was not regenerated after a fixture (or the
     * transpiler) changed. Transpiling needs HHVM's parser: where it cannot
     * run (exit code 3), the committed cases run as they are, and
     * HackConformanceTest::testTranspiledSuiteIsUpToDate skips.
     */
    #[Override]
    public static function setUpBeforeClass(): void
    {
        parent::setUpBeforeClass();

        $output = [];
        $exitCode = 0;
        exec(
            escapeshellarg(PHP_BINARY) . ' '
                . escapeshellarg(__DIR__ . '/../bin/hack-conformance/transpile.php') . ' --check 2>&1',
            $output,
            $exitCode,
        );

        if ($exitCode !== 0 && $exitCode !== 3) {
            /** @var list<string> $output */
            self::fail(implode("\n", $output));
        }
    }

    /**
     * @psalm-pure
     */
    #[Override]
    public function providerValidCodeParse(): iterable
    {
        return [
            'contexts/inout_local_write' => [
                // writing an `inout` parameter is not an effect, and passing a local `inout` to
                // such a function from a `[]` context is fine: the write lands in the caller's own
                // local. Psalm charges a by-reference argument for what it is, nothing for a local.
                'code' => '<?php
                    /** @psalm-capabilities read-props|write-refs */
                    function set_ref(int &$x): void { $x = 1; }

                    /** @psalm-capabilities read-props */
                    function passes_local(): int {
                        $x = 0;
                        set_ref($x);
                        return $x;
                    }

                    /** @psalm-capabilities read-props|write-refs */
                    function passes_own_inout(int &$x): void { set_ref($x); }',
                'assertions' => [],
                'ignored_issues' => [],
                'php_version' => '8.3',
            ],
            'contexts/named_context_constant' => [
                // a class may name a context once (`const ctx Storage = [...]`) and functions
                // refer to it (`[Repo::Storage]`). Psalm spells the alias with `@psalm-type`
                // (and `@psalm-import-type` from other classes) inside `@psalm-capabilities`.
                // The effect is IO because Hack's parse-level property-write check cannot
                // resolve a context constant.
                'code' => '<?php
                    /** @psalm-type Storage = impure */
                    final class Repo {
                        /** @psalm-capabilities Storage|read-props */
                        public function save(): void { echo "saved"; }
                    }

                    /** @psalm-import-type Storage from Repo */
                    final class Service {
                        /** @psalm-capabilities Storage|read-props */
                        public function run(Repo $r): void { $r->save(); }
                    }',
                'assertions' => [],
                'ignored_issues' => [],
                'php_version' => '8.3',
            ],
            'polymorphic_contexts/context_constant_default' => [
                // an abstract context constant with a default is synthesized for the first
                // concrete class that does not define it: the default of Psalm's purity template,
                // `C(...)`, binds C for subclasses without an `@extends` argument.
                'code' => '<?php
                    /** @psalm-purity-template C(read-props) <= read-props|write-this-props|write-props */
                    abstract class Doer {
                        /**
                         * @psalm-capabilities read-props
                         * @psalm-purity-from-template C
                         */
                        public function run(): int { return 1; }
                    }

                    final class DefaultDoer extends Doer {}

                    /** @extends Doer[read-props|write-this-props|write-props] */
                    final class MutatingDoer extends Doer {}

                    /** @psalm-capabilities read-props */
                    function useDefault(DefaultDoer $d): int { return $d->run(); }

                    /** @psalm-capabilities read-props|write-this-props|write-props */
                    function useMutating(MutatingDoer $d): int { return $d->run(); }',
                'assertions' => [],
                'ignored_issues' => [],
                'php_version' => '8.3',
            ],
            'polymorphic_contexts/context_constant_lower_bound_body' => [
                // with `as [write_props]`, a method declared `[this::C]` may use write_props in its
                // body whatever the subclass binds C to. Psalm desugars the lower bound into fixed
                // capabilities of the methods depending on the template.
                'code' => '<?php
                    /** @psalm-capabilities read-props|write-this-props|write-props */
                    function do_write_props(): void {}

                    /** @psalm-purity-template read-props|write-this-props|write-props <= C */
                    abstract class Doer {
                        /**
                         * @psalm-capabilities read-props
                         * @psalm-purity-from-template C
                         */
                        public function run(): void { do_write_props(); }
                    }

                    /** @extends Doer[impure] */
                    final class IoDoer extends Doer {}

                    /** @psalm-impure */
                    function use_io(IoDoer $d): void { $d->run(); }',
                'assertions' => [],
                'ignored_issues' => [],
                'php_version' => '8.3',
            ],
            'polymorphic_contexts/wildcard_context' => [
                // `(function()[_]: int) $f` with `[ctx $f]` makes the function as pure as the
                // closure it is given, without naming a context: Psalm's `Closure[_](): int $f`
                // parameter does the same without declaring a purity template.
                'code' => '<?php
                    /**
                     * @psalm-capabilities read-props
                     * @param Closure[_](): int $f
                     */
                    function apply(Closure $f): int { return $f(); }

                    final class Runner {
                        /**
                         * @psalm-capabilities read-props
                         * @param Closure[_](): int $f
                         */
                        public function run(Closure $f): int { return $f(); }
                    }

                    /** @psalm-capabilities read-props */
                    function use_pure(Runner $r): int { return apply(/** @psalm-capabilities read-props */ fn() => 1) + $r->run(/** @psalm-capabilities read-props */ fn() => 3); }

                    /** @psalm-impure */
                    function use_io(): int { return apply(/** @psalm-impure */ function () { echo "x"; return 1; }); }',
                'assertions' => [],
                'ignored_issues' => [],
                'php_version' => '8.3',
            ],
            'type_variables/array_access' => [
                // nested array access on an element read out of a type-variable list.
                'code' => '<?php
                    /** @template TTValue */
                    final class XIteratorOnArray {
                        /**
                         * @psalm-impure
                         * @param list<TTValue> $array
                         */
                        public function __construct(private array $array = []) {}

                        /**
                         * @psalm-impure
                         * @param Closure(TTValue, TTValue): mixed $func
                         */
                        public function sortBy(Closure $func): void {}

                        /**
                         * @psalm-impure
                         * @return list<TTValue>
                         */
                        public function toArray(): array { return $this->array; }
                    }

                    /** @psalm-impure */
                    function match2(): void {
                        $r = (new XIteratorOnArray([[1, 2]]))->toArray();
                        echo (string)($r[0][0]);
                    }',
                'assertions' => [],
                'ignored_issues' => [],
                'php_version' => '8.3',
            ],
            'type_variables/cast_to_string' => [
                // an element read out of a type-variable `vec<TValue>` can be cast to
                // string through the construction's inferred bound (int).
                'code' => '<?php
                    /** @template TValue */
                    final class XIter {
                        /**
                         * @psalm-impure
                         * @param list<TValue> $array
                         */
                        public function __construct(private array $array) {}

                        /**
                         * @psalm-impure
                         * @param Closure(TValue, TValue): mixed $func
                         */
                        public function sortBy(Closure $func): void {}

                        /**
                         * @psalm-impure
                         * @return list<TValue>
                         */
                        public function toArray(): array { return $this->array; }
                    }

                    /** @psalm-impure */
                    function run(): void {
                        foreach ((new XIter([1]))->toArray() as $v) {
                            echo (string)$v;
                        }
                    }',
                'assertions' => [],
                'ignored_issues' => [],
                'php_version' => '8.3',
            ],
            'type_variables/empty_construction_union_return' => [
                // an empty `new It()` returned where the declared type is a union of two
                // key instantiations of a covariant class. Hack localizes the declared
                // `(It<string> | It<int>)` to `It<(string | int)>` (Typing_union.union_list
                // merges same-class covariant members), so the variable just gains the
                // upper bound `string | int`.
                // Psalm reports the covariant TKey in `sortBy`'s closure parameter (a covariant
                // position, which Hack accepts) unless the method is mutation-free, hence the
                // ignored InvalidTemplateParam.
                'code' => '<?php
                    /** @template-covariant TKey of array-key */
                    final class It {
                        /**
                         * @psalm-impure
                         * @param array<TKey, mixed> $array
                         */
                        public function __construct(array $array = []) {}

                        /**
                         * @psalm-impure
                         * @param Closure(TKey): mixed $func
                         */
                        public function sortBy(Closure $func): void {}
                    }

                    /**
                     * @psalm-impure
                     * @return It<string>|It<int>
                     */
                    function takeNew(): It {
                        return new It();
                    }',
                'assertions' => [],
                'ignored_issues' => ['InvalidTemplateParam'],
                'php_version' => '8.3',
            ],
            'type_variables/method_call_on_element' => [
                // method call on a foreach element of a type-variable list.
                'code' => '<?php
                    final class User {
                        /** @psalm-impure */
                        public function getId(): ?int { return null; }
                    }

                    /** @template TTValue */
                    final class XIteratorOnArray {
                        /**
                         * @psalm-impure
                         * @param list<TTValue> $array
                         */
                        public function __construct(private array $array = []) {}

                        /**
                         * @psalm-impure
                         * @param Closure(TTValue, TTValue): mixed $func
                         */
                        public function sortBy(Closure $func): void {}

                        /**
                         * @psalm-impure
                         * @return list<TTValue>
                         */
                        public function toArray(): array { return $this->array; }
                    }

                    /**
                     * @psalm-impure
                     * @param list<User> $users
                     */
                    function prepareData(array $users): void {
                        $users = (new XIteratorOnArray($users))->toArray();
                        foreach ($users as $user) {
                            $user->getId();
                        }
                    }',
                'assertions' => [],
                'ignored_issues' => [],
                'php_version' => '8.3',
            ],
            'type_variables/multiple_return_types' => [
                // two constructions of a covariant class returned through a union
                // return type. Hack localizes the declared `(It<string> | It<int>)` to
                // `It<(string | int)>` (Typing_union.union_list merges same-class
                // covariant members), so each construction's variable just gains the
                // upper bound `string | int`; the ternary itself unions to It<(int | string)>.
                // Psalm reports the covariant TKey in `sortBy`'s closure parameter (a covariant
                // position, which Hack accepts) unless the method is mutation-free, hence the
                // ignored InvalidTemplateParam.
                'code' => '<?php
                    /** @template-covariant TKey of array-key */
                    final class It {
                        /**
                         * @psalm-impure
                         * @param array<TKey, mixed> $array
                         */
                        public function __construct(array $array = []) {}

                        /**
                         * @psalm-impure
                         * @param Closure(TKey): mixed $func
                         */
                        public function sortBy(Closure $func): void {}
                    }

                    /**
                     * @psalm-impure
                     * @return It<string>|It<int>
                     */
                    function takeNew(): It {
                        return \mt_rand(0, 1) === 0 ? new It([0 => 1]) : new It(["hello" => 1]);
                    }',
                'assertions' => [],
                'ignored_issues' => ['InvalidTemplateParam'],
                'php_version' => '8.3',
            ],
            'type_variables/multiple_return_types_not_covariant' => [
                // same as multiple_return_types.hack but with an invariant key, so Hack
                // cannot merge the declared `(It<string> | It<int>)` into one class type;
                // the ternary stays `(It<int> | It<string>)` and each arm reconciles
                // against its own member of the union.
                // The value goes through a local on purpose: written as a direct
                // `return cond ? new It(...) : new It(...)`, Hack pushes the expected
                // return type into `new` and instantiates the invariant TKey from the
                // FIRST union member (It<string>), so `dict[0 => 1]` is rejected ("must
                // match exactly (it is invariant)") — even a lone
                // `return new It(dict[0 => 1]);` fails that way. That is an artifact of
                // Hack's expected-type propagation, not of its constraint solving, and
                // Psalm does not propagate return types into constructions.
                'code' => '<?php
                    /** @template TKey of array-key */
                    final class It {
                        /**
                         * @psalm-impure
                         * @param array<TKey, mixed> $array
                         */
                        public function __construct(array $array = []) {}

                        /**
                         * @psalm-impure
                         * @param Closure(TKey): mixed $func
                         */
                        public function sortBy(Closure $func): void {}
                    }

                    /**
                     * @psalm-impure
                     * @return It<string>|It<int>
                     */
                    function takeNew(): It {
                        $x = \mt_rand(0, 1) === 0 ? new It([0 => 1]) : new It(["hello" => 1]);
                        return $x;
                    }',
                'assertions' => [],
                'ignored_issues' => [],
                'php_version' => '8.3',
            ],
            'type_variables/nested_construction' => [
                // nested construction; inner element resolves to int and supports arithmetic.
                'code' => '<?php
                    /** @template T */
                    final class Box {
                        /**
                         * @psalm-impure
                         * @param T $value
                         */
                        public function __construct(public $value) {}

                        /**
                         * @psalm-impure
                         * @param Closure(T, T): mixed $func
                         */
                        public function sortBy(Closure $func): void {}
                    }

                    /** @psalm-impure */
                    function nested(): void {
                        $bb = new Box(new Box(5));
                        $inner = $bb->value;
                        $x = $inner->value + 1;
                    }',
                'assertions' => [],
                'ignored_issues' => [],
                'php_version' => '8.3',
            ],
            'type_variables/nested_type_variable_element' => [
                // a construction fed from a container whose element type is itself a
                // type variable resolves through the whole chain to the concrete shape.
                'code' => '<?php
                    /** @template TValue */
                    final class XIter {
                        /**
                         * @psalm-impure
                         * @param array<TValue> $array
                         */
                        public function __construct(private array $array = []) {}

                        /**
                         * @psalm-impure
                         * @param Closure(TValue, TValue): mixed $func
                         */
                        public function sortBy(Closure $func): void {}

                        /**
                         * @psalm-impure
                         * @return array<string, TValue>
                         */
                        public function toAssoc(): array { throw new \Exception("stub"); }

                        /**
                         * @psalm-impure
                         * @return list<TValue>
                         */
                        public function toList(): array { return array_values($this->array); }
                    }

                    /**
                     * @psalm-impure
                     * @param list<array{id: int}> $rows
                     */
                    function run(array $rows): void {
                        $assoc = (new XIter($rows))->toAssoc();
                        $list = (new XIter($assoc))->toList();
                        foreach ($list as $row) {
                            echo $row[\'id\'];
                        }
                    }',
                'assertions' => [],
                'ignored_issues' => [],
                'php_version' => '8.3',
            ],
            'type_variables/property_chain' => [
                // method call reached through a property fetch of a type-variable object.
                'code' => '<?php
                    final class User {
                        /** @psalm-impure */
                        public function getId(): int { return 0; }
                    }

                    /** @template T */
                    final class Box {
                        /**
                         * @psalm-impure
                         * @param T $value
                         */
                        public function __construct(public $value) {}

                        /**
                         * @psalm-impure
                         * @param Closure(T, T): mixed $func
                         */
                        public function sortBy(Closure $func): void {}
                    }

                    /** @psalm-impure */
                    function pchain(): void {
                        $b = new Box(new User());
                        $b->value->getId();
                    }',
                'assertions' => [],
                'ignored_issues' => [],
                'php_version' => '8.3',
            ],
            'type_variables/property_fetch_on_element' => [
                // an element read out of a type-variable `vec<TValue>` is usable as a
                // property-fetch receiver through the construction's inferred bound.
                'code' => '<?php
                    final class User {
                        public int $id = 0;
                    }

                    /** @template TValue */
                    final class XIter {
                        /**
                         * @psalm-impure
                         * @param list<TValue> $array
                         */
                        public function __construct(private array $array = []) {}

                        /**
                         * @psalm-impure
                         * @param Closure(TValue, TValue): mixed $func
                         */
                        public function sortBy(Closure $func): void {}

                        /**
                         * @psalm-impure
                         * @return list<TValue>
                         */
                        public function toArray(): array { return $this->array; }
                    }

                    /**
                     * @psalm-impure
                     * @param list<User> $users
                     */
                    function run(array $users): void {
                        $items = (new XIter($users))->toArray();
                        foreach ($items as $user) {
                            echo $user->id;
                        }
                    }',
                'assertions' => [],
                'ignored_issues' => [],
                'php_version' => '8.3',
            ],
            'SKIPPED-type_variables/typed_closure_param_empty_construction' => [
                // an empty construction assigned to an `ArrayCollection<int, DateTime>`
                // property, then handed a lambda whose param is typed DateTime. The typed
                // lambda param constrains the variable from above; the empty `dict[]`
                // only gives it the lower bound `nothing`. (The original form of
                // ClassTemplateTest::allowPropertyCoercion before PR #11972 changed it.)
                // Skipped, Psalm does not agree with HHVM yet:
                // Psalm types the empty construction ArrayCollection<never, never>
                // and keeps that type after the assignment to the property, so the lambda
                // parameter is checked against never (ParadoxicalCondition) instead of the
                // variable taking DateTime as its upper bound.
                'code' => '<?php
                    /**
                     * @template TKey of array-key
                     * @template T
                     */
                    final class ArrayCollection {
                        /**
                         * @psalm-impure
                         * @param array<TKey, T> $elements
                         */
                        public function __construct(private array $elements = []) {}

                        /**
                         * @psalm-impure
                         * @param Closure(T): bool $p
                         * @return ArrayCollection<TKey, T>
                         */
                        public function filter(Closure $p): ArrayCollection { return $this; }
                    }

                    final class Test {
                        /** @var ArrayCollection<int, DateTime> */
                        private ArrayCollection $c;

                        /** @psalm-impure */
                        public function __construct() {
                            $this->c = new ArrayCollection();
                            $this->c->filter(/** @psalm-impure */ fn(DateTime $dt): bool => $dt === $dt);
                        }
                    }',
                'assertions' => [],
                'ignored_issues' => [],
                'php_version' => '8.3',
            ],
            'type_variables/unbound_closure_param' => [
                // an unbound variable gets only an upper bound from the callable parameter,
                // which is satisfiable, so no error (Hack solves the variable).
                'code' => '<?php
                    final class Item {
                        public int $id = 0;
                    }

                    /** @template T */
                    final class Box {
                        /** @psalm-impure */
                        public function __construct() {}

                        /**
                         * @psalm-impure
                         * @param Closure(T): mixed $cb
                         */
                        public function each(Closure $cb): void {}
                    }

                    /** @psalm-impure */
                    function process(): void {
                        $box = new Box();
                        $box->each(/** @psalm-impure */ fn(Item $item) => $item->id);
                    }',
                'assertions' => [],
                'ignored_issues' => [],
                'php_version' => '8.3',
            ],
            'type_variables/untyped_closure_param' => [
                // an untyped lambda parameter takes the construction's inferred element
                // type (Item), so the property fetch inside the lambda body resolves.
                'code' => '<?php
                    /** @template TValue */
                    final class Coll {
                        /**
                         * @psalm-impure
                         * @param iterable<TValue> $data
                         */
                        public function __construct(iterable $data) {}

                        /**
                         * @psalm-impure
                         * @param Closure(TValue): string $cb
                         */
                        public function each(Closure $cb): void {}
                    }

                    final class Item {
                        public int $id = 0;
                    }

                    /** @psalm-impure */
                    function process(): void {
                        $c = new Coll([new Item()]);
                        $c->each(/** @psalm-impure */ fn($item) => (string)$item->id);
                    }',
                'assertions' => [],
                'ignored_issues' => [],
                'php_version' => '8.3',
            ],
        ];
    }

    /**
     * @psalm-pure
     */
    #[Override]
    public function providerInvalidCodeParse(): iterable
    {
        return [
            'contexts/dynamic_new_context' => [
                // `new $c()` on a classname checks the constructor of that class. Psalm checks
                // the constructor of the class a class-string stands for, and treats an unknown
                // class as impure.
                'code' => '<?php
                    final class Noisy {
                        /** @psalm-impure */
                        public function __construct() { echo "created"; }
                    }

                    /**
                     * @psalm-capabilities read-props
                     * @param class-string<Noisy> $c
                     */
                    function make(string $c): Noisy { return new $c(); }',
                'error_message' => 'ImpureMethodCall',
                'error_levels' => [],
                'php_version' => '8.3',
            ],
            'contexts/function_pointer_context' => [
                // a function pointer carries the context of the function it points to, so
                // calling it needs the same capabilities as calling the function. Psalm's
                // first-class callables carry their capabilities the same way.
                'code' => '<?php
                    /** @psalm-impure */
                    function roll(): int { return 4; }

                    /** @psalm-capabilities read-props */
                    function pure_roll(): int {
                        $r = roll(...);
                        return $r();
                    }',
                'error_message' => 'ImpureFunctionCall',
                'error_levels' => [],
                'php_version' => '8.3',
            ],
            'contexts/readonly_global_getter_leak' => [
                // a readonly value stays readonly through a function that returns it, so the
                // caller cannot mutate it either. Psalm flags the results of callees that may
                // read globals as reached from global state.
                'code' => '<?php
                    final class Box {
                        public int $x = 0;

                        public static ?Box $g = null;
                    }

                    /** @psalm-capabilities read-props|read-globals */
                    function get(): ?Box { return Box::$g; }

                    /** @psalm-capabilities read-props|write-this-props|write-props|read-globals */
                    function leak(): void {
                        $b = get();
                        if ($b !== null) { $b->x = 1; }
                    }',
                'error_message' => 'ImpurePropertyAssignment',
                'error_levels' => [],
                'php_version' => '8.3',
            ],
            'contexts/readonly_global_leak' => [
                // `read_globals` only hands out `readonly` views of static properties, so a
                // function with read_globals and write_props still cannot mutate an object it
                // reached through a static property. Psalm tracks the same thing with the
                // from_global_state flag: mutating such a value needs write-globals.
                'code' => '<?php
                    final class Box {
                        public int $x = 0;

                        public static ?Box $g = null;
                    }

                    /** @psalm-capabilities read-props|write-this-props|write-props|read-globals */
                    function leak(): void {
                        $b = Box::$g;
                        if ($b !== null) { $b->x = 1; }
                    }',
                'error_message' => 'ImpurePropertyAssignment',
                'error_levels' => [],
                'php_version' => '8.3',
            ],
            'contexts/throw_impure_constructor' => [
                // `throw new E()` runs E's constructor like any `new`; there is no exemption for
                // exceptions. Psalm no longer trusts unannotated exception constructors either.
                'code' => '<?php
                    final class MyException extends Exception {
                        /** @psalm-impure */
                        public function __construct() { echo "created"; parent::__construct("x"); }
                    }

                    /** @psalm-capabilities read-props */
                    function fail(): int { throw new MyException(); }',
                'error_message' => 'ImpureMethodCall',
                'error_levels' => [],
                'php_version' => '8.3',
            ],
            'polymorphic_contexts/context_constant_bound' => [
                // `super [write_props]` caps what a subclass may require: the upper bound of
                // Psalm's purity template, checked on `@extends`.
                'code' => '<?php
                    /** @psalm-purity-template C <= read-props|write-this-props|write-props */
                    abstract class Doer {
                        /**
                         * @psalm-capabilities read-props
                         * @psalm-purity-from-template C
                         */
                        public function run(): int { return 1; }
                    }

                    /** @extends Doer[read-props|read-globals|write-globals] */
                    final class GlobalDoer extends Doer {}',
                'error_message' => 'InvalidTemplateParam',
                'error_levels' => [],
                'php_version' => '8.3',
            ],
            'polymorphic_contexts/context_constant_lower_bound' => [
                // `as [write_props]` makes every subclass require at least write_props, so a
                // subclass binding the constant to `[]` is rejected: the lower bound of Psalm's
                // purity template, checked on `@extends`.
                'code' => '<?php
                    /** @psalm-capabilities read-props|write-this-props|write-props */
                    function do_write_props(): void {}

                    /** @psalm-purity-template read-props|write-this-props|write-props <= C */
                    abstract class Doer {
                        /**
                         * @psalm-capabilities read-props
                         * @psalm-purity-from-template C
                         */
                        public function run(): void { do_write_props(); }
                    }

                    /** @extends Doer[read-props] */
                    final class PureDoer extends Doer {}',
                'error_message' => 'InvalidTemplateParam',
                'error_levels' => [],
                'php_version' => '8.3',
            ],
            'polymorphic_contexts/override_dependent_context' => [
                // a method whose context depends on a closure argument promises callers a call as
                // pure as the closures they pass; an override with a fixed context needing more
                // breaks that promise. Psalm compares the unconditional capabilities of the two
                // methods before their worst cases.
                'code' => '<?php
                    final class Box {
                        public int $x = 0;
                    }

                    abstract class Base {
                        /**
                         * @psalm-capabilities read-props
                         * @param Closure[_](): void $f
                         */
                        abstract public function run(Closure $f): int;
                    }

                    final class Mutating extends Base {
                        /**
                         * @psalm-capabilities read-props|write-this-props|write-props
                         * @param Closure(): void $f
                         */
                        #[\Override]
                        public function run(Closure $f): int {
                            $b = new Box();
                            $b->x = 1;
                            return $b->x;
                        }
                    }',
                'error_message' => 'ImmutableDependency',
                'error_levels' => [],
                'php_version' => '8.3',
            ],
            'type_variables/callable_param_conflict' => [
                // a lower bound (int, via set) and an upper bound (Item, via the callable
                // parameter) cannot hold together (Hack: "Expected Item but got int").
                'code' => '<?php
                    final class Item {
                        public int $id = 0;
                    }

                    /** @template T */
                    final class Box {
                        /** @psalm-impure */
                        public function __construct() {}

                        /**
                         * @psalm-impure
                         * @param T $v
                         */
                        public function set($v): void {}

                        /**
                         * @psalm-impure
                         * @param Closure(T): mixed $cb
                         */
                        public function each(Closure $cb): void {}
                    }

                    /** @psalm-impure */
                    function process(): void {
                        $box = new Box();
                        $box->set(5);
                        $box->each(/** @psalm-impure */ fn(Item $item) => $item->id);
                    }',
                'error_message' => 'IncompatibleTypeParameters',
                'error_levels' => [],
                'php_version' => '8.3',
            ],
            'type_variables/mixed_constructor_inference' => [
                // the constructor infers TValue from a mixed-valued container, and the
                // typed lambda parameter then asks for Item: mixed is not Item
                // (Hack: "Expected Item ... But got mixed").
                'code' => '<?php
                    final class Item {
                        public int $id = 0;
                    }

                    /** @template TValue */
                    final class Table {
                        /**
                         * @psalm-impure
                         * @param iterable<array-key, TValue> $data
                         */
                        public function __construct(iterable $data) {}

                        /**
                         * @psalm-impure
                         * @param Closure(TValue): mixed $content
                         */
                        public function column(Closure $content): void {}
                    }

                    /**
                     * @psalm-impure
                     * @param iterable<array-key, mixed> $items
                     */
                    function prepareTable(iterable $items): void {
                        $table = new Table($items);
                        $table->column(/** @psalm-impure */ fn(Item $item): int => $item->id);
                    }',
                'error_message' => 'MixedArgumentTypeCoercion',
                'error_levels' => [],
                'php_version' => '8.3',
            ],
            'type_variables/never_return_not_hidden' => [
                // returning an inhabited variable where `nothing`/`never` is declared is
                // rejected (Hack: "Expected nothing ... invariant ... But got int"). Guards
                // the UnionTypeComparator never-arm fix against false negatives.
                'code' => '<?php
                    /** @template T */
                    final class A {
                        /**
                         * @psalm-impure
                         * @param T $t
                         */
                        public function __construct(private $t) {}

                        /**
                         * @psalm-impure
                         * @param Closure(T, T): mixed $f
                         */
                        public function sortBy(Closure $f): void {}
                    }

                    /**
                     * @psalm-impure
                     * @return A<never>
                     */
                    function f(): A { return new A(5); }',
                'error_message' => 'IncompatibleTypeParameters',
                'error_levels' => [],
                'php_version' => '8.3',
            ],
        ];
    }
}
