name: Pull Request Labels (to be added by maintainers)
on:
  pull_request:
    types: [opened, reopened, labeled, unlabeled, synchronize]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@23e10fde7e062233401931a0eece796cd9bf3177 # v5
        with:
          mode: minimum
          count: 1
          labels: "release:typo, release:fix, release:feature, release:deprecation, release:internal, release:docs, release:removed"
